tempF = int(input("Temperatura em graus Farenheit:"))
tempC = ((tempF-32)*(5/9))
print("Temperatura em graus Celsius: {}".format(tempC))
print("Temperatura em graus Celsius:",tempC)
print("Temperatura em graus Celsius: %f"%(tempC))
print(f"Temperatura em graus Celsius: {tempC}")
print(tempC)
print(f"Temperatura em graus Cº {tempC:.2f}")